### ISSUE TITLE
Adding Support for Particular Files in Gist

### ISSUE THREAD

**Issue by rahulrsingh09** [jasonhodges/ngx-gist#2]
Hi Jason

Thanks for this awsome plugin , however my  requirement was i wanted to read a particular file from my gist which had many .

I have extended this library by forking it to add file support . Hope you like it 
[Added File support](https://github.com/rahulrsingh09/ngx-gist
)

**Comment by jasonhodges** [comment]
Hi @rahulrsingh09 
Took a quick look and I think it is fine. Do you plan to submit a pull request?

**Comment by rahulrsingh09** [comment]
Hi @jasonhodges would love to add a PR . 
One thing is that when a user selects a file option we need to remove the body and add a div as body takes up a lot of unnecessary space . I had forked and made the change , shall i clone it and make a change and have a new branch for that i might need contributer
 access ?

Also @jasonhodges  if you tell me how to pack it as presently when i first load the app it says `ERROR in NgxGistModule is not an NgModule` and then if i build again it works . i just did a npm install and created a dist but what is the general way of packing . 

![image](https://user-images.githubusercontent.com/17721520/29629208-9d68db0c-8855-11e7-8914-f5802d014d1c.png)

This is the error image Please check

**Comment by jasonhodges** [comment]
@rahulrsingh09 
I have added you to a gitter channel, lets chat there

**Comment by jasonhodges** [comment]
closing after successful merge of PR #3
